#!/bin/bash



# use grep to search for lines containing the pattern "bin" in the file /etc/passwd,

# and pipe the output to wc to count the number of lines

grep -c 'bin' /etc/passwd | awk '{print $1}'

